---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---



```{r}
#Importacao do conjunto de dados
options(scipen=10)
library(readxl)
library(dplyr)

df <- read_excel("C:\\Users\\Rodolfo\\Desktop\\Scores\\train.xlsx")


```

```{r}
# Funcoes para Combinar Scores

#Media Simples
f_media_simples<-function(vec,j){
      if(j==1){return(vec[,1])}
      else if (j==2){return((vec[,1]+vec[,2])/2)}
      else if (j==3){return((vec[,1]+vec[,2]+vec[,3])/3)}
      else if (j==4){return((vec[,1]+vec[,2]+vec[,3]+vec[,4])/4)}
      else if (j==5){return((vec[,1]+vec[,2]+vec[,3]+vec[,4]+vec[,5])/5)}
  
}

#Media Geometrica
f_media_geo<-function(vec,j){
      if(j==1){return(vec[,1])}
      else if (j==2){return((vec[,1]*vec[,2])^(1/2))}
      else if (j==3){return((vec[,1]*vec[,2]*vec[,3])^(1/3))}
      else if (j==4){return((vec[,1]*vec[,2]*vec[,3]*vec[,4])^(1/4))}
      else if (j==5){return((vec[,1]*vec[,2]*vec[,3]*vec[,4]*vec[,5])^(1/5))}
  
}

#Media Harmonica
f_media_harm<-function(vec,j){
      if(j==1){return(vec[,1])}
      else if (j==2){return(2/(1/vec[,1]+1/vec[,2]))}
      else if (j==3){return(3/(1/vec[,1]+1/vec[,2]+1/vec[,3]))}
      else if (j==4){return(4/(1/vec[,1]+1/vec[,2]+1/vec[,3]+1/vec[,4]))}
      else if (j==5){return(5/(1/vec[,1]+1/vec[,2]+1/vec[,3]+1/vec[,4]+1/vec[,5]))}
  
}


#Maximo
f_maximo<-function(vec,j){
aux<-rep(0,length(vec[,1]))  
  for(i in 1:length(vec[,1])){
    aux[i]<-max(vec[i,1:j])
    
  }
  return(aux)
  
}

#Stacking
f_stacking<-function(vec,j){
   
     model <-glm(as.factor(vec[,7])~ vec[,1:j],family = binomial(link="logit"))
     return(round(predict.glm(model,type = "response")*100,2))
}
  
```

```{r}
#Fitness
fitness<-function(banco_avaliacao){
  
banco_avaliacao<-  banco_avaliacao%>%
    arrange(desc(Score_final))%>% 
      mutate(N = row_number(desc(Score_final)))%>% 
        filter(N <= 50000) 
            
return(sum(banco_avaliacao$V7))
  
}

```

```{r}

# Elitismo

elite<-function(elem,elem2,popsize){
  
    elem_elite <-  rbind(elem,elem2) %>%
    arrange(desc(V7))%>% 
      mutate(N = row_number(desc(V7)))%>% 
        filter(N <= popsize) 
    
    return(elem_elite[,1:12])
  
}

```


```{r}
#Crossover

GEN_Cross<-function(p_Cross,popsize,elem){

aux_vec<-elem[,6]
aux_regra<-sample(1:popsize,popsize,replace = F)

for(i in 1:popsize){
  
if(p_Cross >= sample(seq(0,1,by=0.01),1)){
  elem[i,7]<-0
  # Troca da regra
  elem[i,6]<-aux_vec[aux_regra[i]]
  elem[aux_regra[i],6]<-aux_vec[i]

  # Selecao de Scores sorteados
  vec<-matrix(0,nrow=length(df$DOCUMENTO),ncol = 7)

    if(elem[i,1]==1){vec[,1]<-df$SCORE_MOTIVOCHAMADA;j=1}
    if(elem[i,2]==1){vec[,2]<-df$SCORE_COMERCIAL;j=2}
    if(elem[i,3]==1){vec[,3]<-df$SCORE_ODC;j=3}
    if(elem[i,4]==1){vec[,4]<-df$SCORE_REPAROS;j=4}
    if(elem[i,5]==1){vec[,5]<-df$SCORE_CHAMADAS;j=5}
    
                      vec[,6]<-df$DOCUMENTO
                      vec[,7]<-df$VAR_TARGET
                      
      # Calculo do Score Combinado
    Score_final<-rep(0,length(df$DOCUMENTO))
         if(elem[i,6]==1){Score_final<-f_media_simples(vec,j)}
    else if(elem[i,6]==2){Score_final<-f_media_geo(vec,j)}
    else if(elem[i,6]==3){Score_final<-f_media_harm(vec,j)}
    else if(elem[i,6]==4){Score_final<-f_maximo(vec,j)}
    else if(elem[i,6]==5){Score_final<-f_stacking(vec,j)}
    
    banco_avaliacao<-as.data.frame(cbind(vec,Score_final))

    # Calculo do fitness
    elem[i,7]<-fitness(banco_avaliacao)
    
}}
     
    return(elem)
  
}

```

```{r}
# Mutacoes

GEN_Mutacao<-function(p_Mutacao,popsize,elem){
 
for(i in 1:popsize){
  
if(p_Mutacao >= sample(seq(0,1,by=0.01),1)){
  elem[i,7]<-0
  
  # Mutacao de Regra
  elem[i,6]<-sample(1:5,1)
  
  aux<-sample(rep(1:5),5,replace = F)
  vec<-matrix(0,nrow=length(df$DOCUMENTO),ncol = 7)
     
    if(elem[i,1]==1){vec[,1]<-as.numeric(as.matrix(df[,aux[1]]));j=1}
    if(elem[i,2]==1){vec[,2]<-as.numeric(as.matrix(df[,aux[2]]));j=2}
    if(elem[i,3]==1){vec[,3]<-as.numeric(as.matrix(df[,aux[3]]));j=3}
    if(elem[i,4]==1){vec[,4]<-as.numeric(as.matrix(df[,aux[4]]));j=4}
    if(elem[i,5]==1){vec[,5]<-as.numeric(as.matrix(df[,aux[5]]));j=5}
    
                      vec[,6]<-df$DOCUMENTO
                      vec[,7]<-df$VAR_TARGET
                      
    # Calculo do Score Combinado
    Score_final<-rep(0,length(df$DOCUMENTO))
         if(elem[i,6]==1){Score_final<-f_media_simples(vec,j)}
    else if(elem[i,6]==2){Score_final<-f_media_geo(vec,j)}
    else if(elem[i,6]==3){Score_final<-f_media_harm(vec,j)}
    else if(elem[i,6]==4){Score_final<-f_maximo(vec,j)}
    else if(elem[i,6]==5){Score_final<-f_stacking(vec,j)}
    
    banco_avaliacao<-as.data.frame(cbind(vec,Score_final))

    # Calculo do fitness
    elem[i,7]<-fitness(banco_avaliacao)
    elem[i,8:12]<-aux
}}
   
    return(elem)

}


```


```{r}

set.seed(123)

GEN_SCORE<-function(popsize,ngeracoes,p_Cross,p_Mutacao){

# Populacao Inicial  
  
#Numero Fixo de Scores
nscores=5

elem<-matrix(0,nrow = popsize, ncol = nscores+7)

for(i in 1:popsize){
  populacao<- sample(1:100,1)
  if(populacao < 23.3){elem[i,1]<- 1 }
  else if(populacao < 43.9){elem[i,1:2]<- 1 }
  else if(populacao < 63.5){elem[i,1:3]<- 1 }
  else if(populacao < 82.4){elem[i,1:4]<- 1 }
  else {elem[i,1:5]<- 1 }
  
  # Sorteio da regra
  elem[i,6]<-sample(1:5,1)

  # Selecao de Scores sorteados
  vec<-matrix(0,nrow=length(df$DOCUMENTO),ncol = 7)

    if(elem[i,1]==1){vec[,1]<-df$SCORE_MOTIVOCHAMADA;j=1}
    if(elem[i,2]==1){vec[,2]<-df$SCORE_COMERCIAL;j=2}
    if(elem[i,3]==1){vec[,3]<-df$SCORE_ODC;j=3}
    if(elem[i,4]==1){vec[,4]<-df$SCORE_REPAROS;j=4}
    if(elem[i,5]==1){vec[,5]<-df$SCORE_CHAMADAS;j=5}
    
                      vec[,6]<-df$DOCUMENTO
                      vec[,7]<-df$VAR_TARGET
                      
  
    # Calculo do Score Combinado
    Score_final<-rep(0,length(df$DOCUMENTO))
         if(elem[i,6]==1){Score_final<-f_media_simples(vec,j)}
    else if(elem[i,6]==2){Score_final<-f_media_geo(vec,j)}
    else if(elem[i,6]==3){Score_final<-f_media_harm(vec,j)}
    else if(elem[i,6]==4){Score_final<-f_maximo(vec,j)}
    else if(elem[i,6]==5){Score_final<-f_stacking(vec,j)}
    
    banco_avaliacao<-as.data.frame(cbind(vec,Score_final))

    # Calculo do fitness
    elem[i,7]<-fitness(banco_avaliacao)
    elem[i,8:12]<-rep(1:5)
}
    elem<-as.data.frame(elem)
      #População Inicial
       print(elem)  
    
    # Crossover e Mutacoes
    for(j in 1:ngeracoes){
        elem2<-GEN_Cross(p_Cross,popsize,elem)
        elem<-as.data.frame(elite(elem,elem2,popsize));rm(elem2)
        elem2<-GEN_Mutacao(p_Mutacao,popsize,elem)
        elem<-as.data.frame(elite(elem,elem2,popsize));rm(elem2)
        print(elem)
      
    }
    return(elem)

}

Selecionados<-GEN_SCORE(popsize = 20,ngeracoes=10,p_Cross=1,p_Mutacao=1)


```